
name: Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
              distribution: "temurin"
              java-version: 17

      - name: API_KEY
        env:
          API_KEY: ${{secrets.API_KEY}}
        run: echo API_KEY=\"$API_KEY\" > local.properties

      - name: Run Lint Test
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v3
        with:
          name: lint-results-test-report.html
          path: presentation/build/reports/lint-results-debug.html

      - name: List Contents of Directory
        run: ls -R presentation/build/reports
